version: '3.7'
services:
    bodypix:
        image: bodypix
        init: true
        build:
            context: ./bodypix
        read_only: true

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./fakecam
        read_only: true
        volumes:
            - ${BACKGROUND_IMAGE_PATH}:/src/background.jpg:ro
            - ${FOREGROUND_IMAGE_PATH}:/src/foreground.jpg:ro
            - ${FOREGROUND_MASK_IMAGE_PATH}:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - ${INPUT_DEVICE}:/dev/video0
            # output (virtual webcam)
            - ${OUTPUT_DEVICE}:/dev/video2
        depends_on:
            - bodypix
        command: --bodypix-url http://bodypix:9000/ ${FAKE_PY_ADDITIONAL_OPTIONS_CPU}
