version: '3.7'

# We use a cache for CUDA so only the first startup takes a lot of time (> 5 min.)
# https://developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching/

services:
    bodypix-gpu:
        image: bodypix-gpu
        init: true
        build:
            context: ./bodypix
            dockerfile: Dockerfile-gpu
        read_only: true
        volumes:
            - communication_volume:/socket
            - compute_cache:/root/.nv/ComputeCache
        environment:
            - PORT=/socket/bodypix.sock
            - CUDA_CACHE_MAXSIZE=2147483647
            - CUDA_CACHE_DISABLE=0
            - CUDA_CACHE_PATH=/root/.nv/ComputeCache
        shm_size: 1gb
        ulimits:
            memlock: -1
            stack: 67108864
        runtime: nvidia

    fakecam-gpu:
        image: fakecam-gpu
        init: true
        build:
            context: ./fakecam
        read_only: true
        volumes:
            - communication_volume:/socket
            - ${BACKGROUND_IMAGE_PATH}:/src/background.jpg:ro
            - ${FOREGROUND_IMAGE_PATH}:/src/foreground.jpg:ro
            - ${FOREGROUND_MASK_IMAGE_PATH}:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - ${INPUT_DEVICE}:/dev/video0
            # output (virtual webcam)
            - ${OUTPUT_DEVICE}:/dev/video2
        depends_on:
            - bodypix-gpu
        command: --bodypix-url /socket/bodypix.sock ${FAKE_PY_ADDITIONAL_OPTIONS_GPU}

volumes:
    communication_volume:
    compute_cache:
